# Generated by Django 4.2.7 on 2023-11-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_payment_token_alter_payment_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="cardholder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="expiry_month",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="expiry_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
