# Generated by Django 4.2.6 on 2023-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_card_number_payment_cardholder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discounted_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
