# Generated by Django 4.2.7 on 2023-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="discounted_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=models.DecimalField(
                    blank=True, decimal_places=2, max_digits=10, null=True
                ),
                max_digits=10,
            ),
        ),
    ]
