# Generated by Django 4.2.6 on 2023-11-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="car_id",
        ),
        migrations.RemoveField(
            model_name="account",
            name="car_title",
        ),
        migrations.RemoveField(
            model_name="account",
            name="customer_need",
        ),
    ]
