# Generated by Django 4.2.6 on 2023-12-05 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_remove_account_car_id_remove_account_car_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="message",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_id",
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
