# Generated by Django 4.2.6 on 2023-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="dropoff_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="dropoff_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="car",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
