# Generated by Django 4.2.6 on 2023-11-20 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_dropoff_date_car_dropoff_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="dropoff_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.today, null=True
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="dropoff_location",
            field=models.CharField(
                choices=[
                    ("NewYork", "New York City Office"),
                    ("LosAngeles", "Los Angeles Downtown Office"),
                    ("Chicago", "Chicago Central Office"),
                    ("Houston", "Houston Branch Office"),
                    ("Phoenix", "Phoenix Airport Office"),
                    ("Philadelphia", "Philadelphia City Center Office"),
                    ("SanAntonio", "San Antonio Suburban Office"),
                    ("SanDiego", "San Diego Beachside Office"),
                    ("Dallas", "Dallas Business District Office"),
                    ("SanJose", "San Jose University Area Office"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="pickup_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.today, null=True
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("NewYork", "New York City Office"),
                    ("LosAngeles", "Los Angeles Downtown Office"),
                    ("Chicago", "Chicago Central Office"),
                    ("Houston", "Houston Branch Office"),
                    ("Phoenix", "Phoenix Airport Office"),
                    ("Philadelphia", "Philadelphia City Center Office"),
                    ("SanAntonio", "San Antonio Suburban Office"),
                    ("SanDiego", "San Diego Beachside Office"),
                    ("Dallas", "Dallas Business District Office"),
                    ("SanJose", "San Jose University Area Office"),
                ],
                max_length=100,
            ),
        ),
    ]
