# Generated by Django 4.2.6 on 2023-11-17 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("user_id", models.IntegerField(blank=True)),
                ("car_id", models.IntegerField()),
                ("car_title", models.CharField(max_length=100)),
                ("pickup_date", models.CharField(max_length=100)),
                ("dropoff_date", models.DateField()),
                ("pickup_location", models.CharField(max_length=100)),
                ("dropoff_location", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                (
                    "create_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
