# Generated by Django 4.2.6 on 2023-11-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="car_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="car_title",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="dropoff_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="dropoff_location",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pickup_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pickup_location",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user_id",
        ),
    ]
