# Generated by Django 4.2.6 on 2023-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_car_title_order_city_order_dropoff_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="car_id",
            field=models.IntegerField(default=1),
        ),
    ]
