# Generated by Django 4.2.6 on 2023-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_car_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="car_id",
            field=models.IntegerField(),
        ),
    ]
