# Generated by Django 4.2.6 on 2023-11-20 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_contact_user_type"),
        ("orders", "0005_remove_order_user_id_alter_order_car_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contacts.contact",
            ),
        ),
    ]
