# Generated by Django 4.2.6 on 2023-11-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_dropoff_date_alter_car_dropoff_location_and_more"),
        ("orders", "0008_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="car_id",
        ),
        migrations.AddField(
            model_name="order",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cars.car",
            ),
        ),
    ]
