# Generated by Django 4.2.7 on 2023-11-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_dropoff_date_alter_car_dropoff_location_and_more"),
        ("orders", "0010_alter_order_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
    ]
