# Generated by Django 4.2.7 on 2023-11-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="promo_code_applied",
            field=models.BooleanField(default=False),
        ),
    ]
