# Generated by Django 4.2.7 on 2023-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discounted_amount_input",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code_input",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
