# Generated by Django 4.2.7 on 2023-12-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0014_order_discounted_amount_input_order_promo_code_input_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discounted_amount_input",
        ),
        migrations.RemoveField(
            model_name="order",
            name="promo_code_input",
        ),
    ]
